# Goals for this session

1. Perform EVD
2. Explore properties of EVD
3. Perform SVD 
4. Explore properties of SVD
5. Be able to explain differences and relationships between EVD and SVD

In [1]:
import numpy as np
np.set_printoptions(suppress=True) # make floats display nicer

# 1. Eigen Value Decomposition



### What are Eigenvalues and Eigenvectors?

Think of a (n X n) matrix $A$ as a linear operator. When you multiply a vector $x$ with $A$, you are performing operations upon $x$ such as rotation and scaling. 

<i> Eigenvectors </i> are special vectors that do not become rotated when multipled with A. Instead, you get them back scaled by a scalar, called <i> eigenvalue</i>. 

In other words, following holds for an eigenvector $v$ : $Av = \lambda v$ 


### What is EVD?

Performing Eigen Value Decomposition (EVD) is to do the following:

$ A = V W V^{-1} $

Where:   
$V$ is the square matrix whose columns are the eigenvectors   
W is the diagnoal matrix whose diagnomal elements are the corresponding eigenvalues. 

To demonstrate EVD, We will be using Numpy's linalg.eig function, whose detailed documentation can be found here:  
https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linalg.eig.html


In [2]:
n = 5
A = np.random.rand(n, n)
A_sim = np.tril(A) + np.tril(A, -1).T
A_sim

array([[ 0.35546919,  0.95257726,  0.99315819,  0.7345501 ,  0.55192272],
       [ 0.95257726,  0.4760352 ,  0.69373909,  0.64294787,  0.82544256],
       [ 0.99315819,  0.69373909,  0.30563077,  0.84714437,  0.91549045],
       [ 0.7345501 ,  0.64294787,  0.84714437,  0.34152619,  0.88031864],
       [ 0.55192272,  0.82544256,  0.91549045,  0.88031864,  0.85774031]])

In [3]:
w, v = np.linalg.eigh(A_sim)
print "Eigenvalues", w

print "\nEach column is an eigenvector \n"
print v

Eigenvalues [-0.81317633 -0.47990561 -0.2031639   0.13999356  3.69265395]

Each column is an eigenvector 

[[ 0.66085958  0.22283288  0.10497456  0.56127978 -0.43307675]
 [-0.34385187 -0.287847   -0.7133998   0.31629629 -0.43580658]
 [-0.6038585   0.51485108  0.39698233  0.08220181 -0.4537964 ]
 [-0.002065   -0.74353645  0.50445824 -0.1220526  -0.42163293]
 [ 0.2835157   0.22264665 -0.26070668 -0.75051162 -0.48868359]]


# 2. Exploring Properties of EVD

### Property 1. Only diagonalizable matrices can be decomposed 

This means that the (n x n) matrix must have n linearly independent eigenvectors. 

In [4]:
A_invalid = np.ones((2,2))
A_invalid[1,0] = 0
print "A non-diagnolizable matrix\n", A_invalid, '\n'

w_invalid, v_invalid = np.linalg.eig(A_invalid)
print "After decomposition...."
print "Eigenvalues: ", w_invalid, '\n\nA_INVALID CANNOT BE DIAGONLIZED.\n', v_invalid

A non-diagnolizable matrix
[[ 1.  1.]
 [ 0.  1.]] 

After decomposition....
Eigenvalues:  [ 1.  1.] 

A_INVALID CANNOT BE DIAGONLIZED.
[[ 1. -1.]
 [ 0.  0.]]


### Property 2. $Av = \lambda v$  

Let $\lambda_{1} ... \lambda_{n}$ be series of eigenvalues
Let $v_{1} ... v_{n}$ be series of eigenvectors. Then, 

A$v_{1}$ = $\lambda_{1}v_{1} \\$  
A$v_{2}$ = $\lambda_{2}v_{2} \\$  
...  
A$v_{n}$ = $\lambda_{n}v_{n} \\$


<b> In python notation, </b>

dot(A[:,:], v[:,i]) = w[i] * v[:,i] for $i \in \{0,...,M-1\}$



In [5]:
for i in range(0, 5):
    print "Checking eigenvalue ", i, "..."
    print np.dot(A_sim, v[:,i])
    print np.dot(w[i], v[:, i])

Checking eigenvalue  0 ...
[-0.53739537  0.2796122   0.49104344  0.00167921 -0.23054826]
[-0.53739537  0.2796122   0.49104344  0.00167921 -0.23054826]
Checking eigenvalue  1 ...
[-0.10693875  0.13813939 -0.24707992  0.35682732 -0.10684938]
[-0.10693875  0.13813939 -0.24707992  0.35682732 -0.10684938]
Checking eigenvalue  2 ...
[-0.02132704  0.14493709 -0.08065248 -0.1024877   0.05296619]
[-0.02132704  0.14493709 -0.08065248 -0.1024877   0.05296619]
Checking eigenvalue  3 ...
[ 0.07857556  0.04427945  0.01150772 -0.01708658 -0.1050668 ]
[ 0.07857556  0.04427945  0.01150772 -0.01708658 -0.1050668 ]
Checking eigenvalue  4 ...
[-1.59920258 -1.60928287 -1.67571306 -1.55694451 -1.8045394 ]
[-1.59920258 -1.60928287 -1.67571306 -1.55694451 -1.8045394 ]


### Property 3. Vector norm of eigenvectors

||$V_{i}$|| = 1



In [6]:
print np.sum(v**2, axis=0)

[ 1.  1.  1.  1.  1.]


### Property 4. Similarity between eigenvectors

$V_{i}^{T} V_{j}$

= 1 if $i = j$,  
  0 if $i \neq j$

This means that inner product between eigenvectors are 0 if they are distinct vectors.  
Intuitively, this means that they are linearly independent (share no similarity)

In [7]:
for i in range(0, 5):
    for j in range(0, 5):
        print "Indices", (i, j), "Inner Product ", '{:.2f}'.format(np.inner(v[:, i], v[:, j]))

Indices (0, 0) Inner Product  1.00
Indices (0, 1) Inner Product  -0.00
Indices (0, 2) Inner Product  0.00
Indices (0, 3) Inner Product  -0.00
Indices (0, 4) Inner Product  -0.00
Indices (1, 0) Inner Product  -0.00
Indices (1, 1) Inner Product  1.00
Indices (1, 2) Inner Product  -0.00
Indices (1, 3) Inner Product  -0.00
Indices (1, 4) Inner Product  -0.00
Indices (2, 0) Inner Product  0.00
Indices (2, 1) Inner Product  -0.00
Indices (2, 2) Inner Product  1.00
Indices (2, 3) Inner Product  -0.00
Indices (2, 4) Inner Product  -0.00
Indices (3, 0) Inner Product  -0.00
Indices (3, 1) Inner Product  -0.00
Indices (3, 2) Inner Product  -0.00
Indices (3, 3) Inner Product  1.00
Indices (3, 4) Inner Product  0.00
Indices (4, 0) Inner Product  -0.00
Indices (4, 1) Inner Product  -0.00
Indices (4, 2) Inner Product  -0.00
Indices (4, 3) Inner Product  0.00
Indices (4, 4) Inner Product  1.00


### Things to watch out for

- Many matrices are NOT diagnolizable and may have complex eigenvalues as seen in lecture.   
If you know that eigen values must be REAL Because A is a positive definite matrix, then use "np.real_if_close(x)"

# 3. Singular Value Decomposition 

What if you want to decompose a non-square matrix? You cannot do this with EVD. Why? 

Think about the dimensions of matrices and vectors when you perform $Av = \lambda v$. If $A$ was a (n x m) matrix, then v must be a (m x 1) vector, yielding $Av$ to be a (n x 1)  vector. This means the right side of the equation also has to yield a (n x 1) dimensional vector, but $v$ was a (m x 1) vector to begin with. Since A is a non-square matrix, $ m \neq n$. 

This means that we need a more genrealized method for matrix decomposition, and this is precisely what SVD is used for. 

SVD of a matrx A does the following:

$A = U S V^{T} $

where:
$A$ is a (m x n) matrix  
$U$ is a $m * m$ orthonormal matrix of 'left-singular' (eigen)vectors of $AA^{T}$,  
$V^{T}$ is a $n * n$ orthonormal matrix of 'right-singular' (eigen)vectors of $A^{T}A$  
$S$ is a $m * n$ diagonal matrix of the square root of nonzero eigenvalues (called singular values denoted by $\sigma$)  of $U$ _or_ $V$, ordered by decreasing size. 

There are many applications with SVD as solving systems of differential equations, linear systems, etc. Later in the course, we will be using an unsupervised learning technique called PCA (Principle Component Analysis) whose fundamentals are based on EVD.

We use numpy.linalg.svd to demonstrate SVD technique whose detailed documentation can be found here:  
https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linalg.svd.html

In [8]:
n = 5
m = 3
A2 = np.random.rand(n, m)
A2

array([[ 0.45409562,  0.95750328,  0.62803589],
       [ 0.59879734,  0.70860408,  0.72816308],
       [ 0.42239604,  0.30888262,  0.33327031],
       [ 0.96237593,  0.47385069,  0.36784239],
       [ 0.43818576,  0.28713574,  0.84710018]])

In [9]:
U, s, V = np.linalg.svd(A2, full_matrices=True)

print U, '\n\n', s, '\n\n' ,V

[[-0.52364587  0.43663522  0.58583497 -0.4132516   0.1454826 ]
 [-0.52295883  0.16700892  0.01183859  0.83327795 -0.06426348]
 [-0.27321724 -0.15272359 -0.0499458  -0.21145363 -0.9245651 ]
 [-0.46199454 -0.8285112   0.05964336 -0.10210217  0.2935099 ]
 [-0.4052437   0.26777305 -0.80660109 -0.28237118  0.18367451]] 

[ 2.24834516  0.54821116  0.4644252 ] 

[[-0.57309793 -0.57448111 -0.58440586]
 [-0.8139858   0.31656745  0.48704433]
 [-0.09479389  0.75482217 -0.64904362]]


Each element of the vector in the middle are singular values. You may have expected a diagnomal matrix whose diagnoals are singular value, but this vector essentially is a compressed form of that diagnomal matrix.

In other words, we can re-shape this vector.

In [10]:
s_reshaped = np.concatenate((np.diag(s), np.zeros((n - len(s), m))))
s_reshaped

array([[ 2.24834516,  0.        ,  0.        ],
       [ 0.        ,  0.54821116,  0.        ],
       [ 0.        ,  0.        ,  0.4644252 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

# 4. Exploring Properties of SVD

### Property 1. U and V are orthonormal matrices

In [11]:
print np.dot(V, V.T), '\n'
print np.dot(U, U.T)

[[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]] 

[[ 1.  0. -0.  0.  0.]
 [ 0.  1.  0. -0.  0.]
 [-0.  0.  1.  0.  0.]
 [ 0. -0.  0.  1. -0.]
 [ 0.  0.  0. -0.  1.]]


@TODO more properties to be discussed in next lecture. 

## Restoring A From U, s, V 

We can reconstruct A with U, s_reshaped, V

In [12]:
A2_restored = np.dot(U, np.dot(s_reshaped, V))
print A2_restored
print "\n Compare with original....\n "
print A2

[[ 0.45409562  0.95750328  0.62803589]
 [ 0.59879734  0.70860408  0.72816308]
 [ 0.42239604  0.30888262  0.33327031]
 [ 0.96237593  0.47385069  0.36784239]
 [ 0.43818576  0.28713574  0.84710018]]

 Compare with original....
 
[[ 0.45409562  0.95750328  0.62803589]
 [ 0.59879734  0.70860408  0.72816308]
 [ 0.42239604  0.30888262  0.33327031]
 [ 0.96237593  0.47385069  0.36784239]
 [ 0.43818576  0.28713574  0.84710018]]


# Exploring Relationship between PCA & SVD

Between PCA and SVD, following must hold:

$$
Given, A = X.T * X \\
(1)  A = V * D * V.T \\ 
(2)  X = U * S * V.T \\
(3)  D = S^{2}  \\
$$

In [13]:
n = 5
d = 3

X = np.random.randn(d, n)
print "Printing X....\n"
print X

A = np.dot(X.T, X)
print "\n Printing A....\n"
print A 

w_eig, v_eig = np.linalg.eigh(A)
print "\nPrinting V, D, V^{T} ....\n"
print v_eig, '\n', np.diag(w_eig), '\n', v_eig.T


print "\nIs A = V * D * V^{T} ? \n"
print np.dot(np.dot(v_eig,np.diag(w_eig)), v_eig.T)
print "\nYes! (Compare with A above)"

Printing X....

[[ 0.03939407 -0.39529962  1.37107684 -1.52521564  1.03173972]
 [ 1.09709888  0.17177067  0.73687298 -1.72359187 -0.71555706]
 [-0.14900177  0.94422293 -0.457225   -0.69309068 -0.10124728]]

 Printing A....

[[ 1.22737938  0.03218607  0.93056215 -1.84776343 -0.7293064 ]
 [ 0.03218607  1.0773239  -0.84713531 -0.3475775  -0.62635804]
 [ 0.93056215 -0.84713531  2.63188817 -3.04435773  0.93361256]
 [-1.84776343 -0.3475775  -3.04435773  5.77742641 -0.27012368]
 [-0.7293064  -0.62635804  0.93361256 -0.27012368  1.58675977]]

Printing V, D, V^{T} ....

[[-0.03153176  0.74625908  0.50995098  0.32836923 -0.27244591]
 [ 0.5992715   0.23237271 -0.59776307  0.47846958  0.02495533]
 [ 0.69119719 -0.17378891  0.28552977 -0.39841567 -0.5017784 ]
 [ 0.38461723  0.18767565  0.32253609 -0.21253512  0.81709652]
 [-0.11914466  0.56892492 -0.44392851 -0.67774205 -0.07564503]] 
[[-0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0

In [14]:
u_svd, s, v_svd = np.linalg.svd(X)

print "Printing X ....\n"

print X

print "\nPrinting U, S, V^{T} ....\n"
s_concat = np.concatenate((np.diag(s), np.zeros((n - d, d)))).T

print u_svd, '\n', s_concat, '\n', v_svd

print "\n Is X = U * S * V.T?"
print np.dot(np.dot(u_svd, s_concat), v_svd)

print "\n Yes! (Compare with X above)"

Printing X ....

[[ 0.03939407 -0.39529962  1.37107684 -1.52521564  1.03173972]
 [ 1.09709888  0.17177067  0.73687298 -1.72359187 -0.71555706]
 [-0.14900177  0.94422293 -0.457225   -0.69309068 -0.10124728]]

Printing U, S, V^{T} ....

[[-0.70657913  0.65054211  0.27846167]
 [-0.70161028 -0.59280681 -0.39537717]
 [-0.09213552 -0.47473683  0.87529194]] 
[[ 2.8770574   0.          0.          0.          0.        ]
 [ 0.          1.68713605  0.          0.          0.        ]
 [ 0.          0.          1.08484576  0.          0.        ]] 
[[-0.27244591  0.02495533 -0.5017784   0.81709652 -0.07564503]
 [-0.32836923 -0.47846958  0.39841567  0.21253512  0.67774205]
 [-0.50995098  0.59776307 -0.28552977 -0.32253609  0.44392851]
 [ 0.74655523  0.18761998 -0.22420741  0.1588484   0.57615297]
 [ 0.02349799  0.61475373  0.67652581  0.39739118 -0.07693354]]

 Is X = U * S * V.T?
[[ 0.03939407 -0.39529962  1.37107684 -1.52521564  1.03173972]
 [ 1.09709888  0.17177067  0.73687298 -1.72359187 -0.7

In [15]:
import math
print "Does sqrt(eigenvalues) == singular values hold true?"

print "Printing singular values...."
print list(reversed(s))

print "\nPrinting eigenvalues...."
print w_eig

print "\nPrinting squared singular values...."
print list(reversed([e**2 for e in s]))


Does sqrt(eigenvalues) == singular values hold true?
Printing singular values....
[1.0848457591655354, 1.6871360462405252, 2.8770573979185197]

Printing eigenvalues....
[-0.          0.          1.17689032  2.84642804  8.27745927]

Printing squared singular values....
[1.1768903211794468, 2.8464280385241114, 8.2774592709176833]
