In [1]:
import numpy as np
import time

In [2]:
# avoid for loop
# re-organize computatoin to speed things up. 

A = np.array([2, 3, 4])

In [3]:
print A

[2 3 4]


In [4]:
print A.shape

(3L,)


In [5]:
A = np.array([[2,3,4]])

In [6]:
print A.shape

(1L, 3L)


In [7]:
print A.transpose()

[[2]
 [3]
 [4]]


In [8]:
B = np.array([[2,3,4],[5,6,7]])

In [9]:
print B

[[2 3 4]
 [5 6 7]]


In [10]:
C = np.random.rand(3, 5)

In [11]:
print C

[[ 0.01281912  0.8994938   0.67330084  0.50507029  0.5480133 ]
 [ 0.01259382  0.55612777  0.15540983  0.63100436  0.42677098]
 [ 0.02461232  0.82153616  0.56922867  0.9417139   0.54813214]]


In [12]:
D = np.random.randn(3, 5)

In [13]:
print D

[[ 1.46268962 -2.43303637  1.13827287 -0.70339552  1.40276814]
 [-1.79136156 -0.02666333 -0.79280865 -0.11956946 -0.08716137]
 [-0.18842991 -0.72522142 -0.36657157  1.13856859 -0.84178757]]


In [15]:
Z = np.zeros((3, 5))

In [16]:
print Z

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [17]:
O = np.ones((3,5))

In [18]:
print O

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [19]:
D = np.diag(np.arange(10))
print D

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


In [20]:
print np.arange(10)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
A = np.arange(20)
print A

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
A.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
A = np.random.rand(3, 5)

In [24]:
B = np.random.rand(3, 5)

In [25]:
print A, B

[[ 0.46364973  0.10423791  0.09634227  0.7967927   0.19425797]
 [ 0.00924519  0.27063253  0.65596312  0.11454223  0.41174864]
 [ 0.97410649  0.93350112  0.85503566  0.41026753  0.99023657]] [[ 0.40792174  0.9013799   0.01553005  0.35327274  0.52952229]
 [ 0.24303907  0.16349721  0.75512525  0.86574608  0.48374849]
 [ 0.78305605  0.49905654  0.42901185  0.7382141   0.39110881]]


In [26]:
print A

[[ 0.46364973  0.10423791  0.09634227  0.7967927   0.19425797]
 [ 0.00924519  0.27063253  0.65596312  0.11454223  0.41174864]
 [ 0.97410649  0.93350112  0.85503566  0.41026753  0.99023657]]


In [27]:
print B

[[ 0.40792174  0.9013799   0.01553005  0.35327274  0.52952229]
 [ 0.24303907  0.16349721  0.75512525  0.86574608  0.48374849]
 [ 0.78305605  0.49905654  0.42901185  0.7382141   0.39110881]]


In [28]:
C = A + B
print C

[[ 0.87157147  1.00561781  0.11187232  1.15006544  0.72378026]
 [ 0.25228427  0.43412974  1.41108837  0.98028831  0.89549713]
 [ 1.75716254  1.43255765  1.28404751  1.14848163  1.38134537]]


In [29]:
C = A * B
print C

[[ 0.1891328   0.09395796  0.0014962   0.28148514  0.10286392]
 [ 0.00224694  0.04424766  0.49533432  0.09916449  0.19918278]
 [ 0.76277998  0.46586983  0.36682043  0.30286527  0.38729024]]


In [31]:
C1 = np.zeros((3,5))
print C1

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [32]:
for i in range(3):
    for j in range(5): 
        C1[i,j] = A[i,j] * B[i,j]

In [33]:
print C - C1

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [34]:
D = np.dot(A, B)

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [35]:
D = np.dot(A, B.T)

In [36]:
print D

[[ 0.66893602  0.98627024  1.12059591]
 [ 0.51639592  0.84017619  0.6693116 ]
 [ 1.92136578  1.86924273  2.28562576]]


In [37]:
D1 = np.zeros((3,3))

In [38]:
for i in range(3):
    for j in range(3):
        for k in range(5): 
            D1[i,j] += A[i,k] * B.T[k,j]

In [39]:
print D1

[[ 0.66893602  0.98627024  1.12059591]
 [ 0.51639592  0.84017619  0.6693116 ]
 [ 1.92136578  1.86924273  2.28562576]]


In [40]:
print D

[[ 0.66893602  0.98627024  1.12059591]
 [ 0.51639592  0.84017619  0.6693116 ]
 [ 1.92136578  1.86924273  2.28562576]]


In [41]:
print A

[[ 0.46364973  0.10423791  0.09634227  0.7967927   0.19425797]
 [ 0.00924519  0.27063253  0.65596312  0.11454223  0.41174864]
 [ 0.97410649  0.93350112  0.85503566  0.41026753  0.99023657]]


In [42]:
A *= 3
print A

[[ 1.39094918  0.31271372  0.2890268   2.3903781   0.5827739 ]
 [ 0.02773558  0.8118976   1.96788937  0.3436267   1.23524591]
 [ 2.92231947  2.80050335  2.56510699  1.23080259  2.9707097 ]]


In [43]:
A += 3

In [44]:
print A

[[ 4.39094918  3.31271372  3.2890268   5.3903781   3.5827739 ]
 [ 3.02773558  3.8118976   4.96788937  3.3436267   4.23524591]
 [ 5.92231947  5.80050335  5.56510699  4.23080259  5.9707097 ]]


In [45]:
sa = np.zeros(3)

In [46]:
print sa

[ 0.  0.  0.]


In [47]:
for i in range(3): 
    for j in range(5):
        sa[i] += A[i,j]

In [48]:
print sa

[ 19.96584171  19.38639516  27.48944209]


In [49]:
print A.sum(axis=0)

[ 13.34100423  12.92511467  13.82202316  12.96480739  13.7887295 ]


In [51]:
print A.sum(axis=1)

[ 19.96584171  19.38639516  27.48944209]


In [52]:
print A.max(axis=0)

[ 5.92231947  5.80050335  5.56510699  5.3903781   5.9707097 ]


In [53]:
print A

[[ 4.39094918  3.31271372  3.2890268   5.3903781   3.5827739 ]
 [ 3.02773558  3.8118976   4.96788937  3.3436267   4.23524591]
 [ 5.92231947  5.80050335  5.56510699  4.23080259  5.9707097 ]]


In [54]:
B = np.sqrt(A)
print B

[[ 2.09545918  1.82008619  1.81356742  2.32171878  1.89282168]
 [ 1.74003896  1.95240815  2.22887626  1.82855864  2.05797131]
 [ 2.43358161  2.40842341  2.3590479   2.05689149  2.44350357]]


In [56]:
np.sqrt(A[0,0])

2.0954591811749226

In [64]:
n = 100
m = 300
A = np.random.randn(n, m)
B = np.random.randn(n, m)
C = np.zeros((n, n))
t1 = time.time()
for i in range(n):
    for j in range(n):
        for k in range(m):
            C[i,j] += A[i,k] * B.T[k,j]
t2 = time.time()
print t2 - t1

3.18299984932


In [73]:
n = 5000
m = 300
A = np.random.randn(n, m)
B = np.random.randn(n, m)
t3 = time.time()
C1 = np.dot(A, B.T)
t4 = time.time()
print t4 - t3

0.426999807358


In [79]:
w = np.random.randn(n, 1)
wt = np.zeros((m,1))
t1 = time.time()
for i in range(m):
    for j in range(n):
        wt[i] += B.T[i,j] * w[j]
t2 = time.time()
print t2 - t1

4.26499986649


In [78]:
t3 = time.time()
wt = np.dot(B.T, w)
t4 = time.time()
print t4 - t3

0.0269999504089


In [80]:
n = 5000
m = 300
w = np.random.randn(n, 1)
A = np.random.randn(n, m)
B = np.random.randn(n, m)

t1 = time.time()
v = np.dot(np.dot(A, B.T), w)
t2 = time.time()

t3 = time.time()
v2 = np.dot(A, np.dot(B.T, w))
t4 = time.time()

print t2-t1, t4-t3

0.430999994278 0.0


In [83]:
n = 1
m = 5000
l = 5000
A = np.random.randn(n, m)
B = np.random.randn(m, l)
C = np.random.randn(l, n)

t1 = time.time()
a1 = np.trace(np.dot(np.dot(A, B), C))
t2 = time.time()
a2 = np.trace(np.dot(np.dot(B, C), A))
t3 = time.time()
a3 = np.trace(np.dot(np.dot(C, A), B))
t4 = time.time()

print a1, a2, a3

print t2-t1, t3-t2, t4-t3

2726.08447969 2726.08447969 2726.08447969
0.00999999046326 0.0899999141693 7.0720000267


In [84]:
print A.shape, B.shape

(1L, 5000L) (5000L, 5000L)


In [87]:
D = np.vstack((A, B))

In [88]:
print D.shape

(5001L, 5000L)


In [89]:
print C.shape

(5000L, 1L)


In [91]:
E = np.hstack((B,C))

In [92]:
print E.shape

(5000L, 5001L)


In [101]:
A = np.random.randn(10, 10)

In [102]:
A = A * A.T

In [103]:
print A

[[ 0.90646794 -0.36369975 -1.87483706  0.45298803  0.12268087  0.022954
  -0.00796362  0.74801245  0.10650752  0.0494469 ]
 [-0.36369975  1.52031226  5.30907245  0.00768765 -0.90123703  0.34338958
   0.67307372 -2.8544615   0.767813   -0.01597416]
 [-1.87483706  5.30907245  0.14595197 -1.04350859  1.89367101 -0.78873008
   0.0226291   0.04439682 -1.11326715  0.45909311]
 [ 0.45298803  0.00768765 -1.04350859  1.36978251 -0.02270202 -0.05659131
  -0.21661932 -0.41496501  0.58838947  0.69747529]
 [ 0.12268087 -0.90123703  1.89367101 -0.02270202  0.68678776  0.91135106
  -0.10774987 -0.44598552 -1.49653517 -0.43029485]
 [ 0.022954    0.34338958 -0.78873008 -0.05659131  0.91135106  1.21910266
  -0.1918078   0.24824484 -0.68089578 -2.63428079]
 [-0.00796362  0.67307372  0.0226291  -0.21661932 -0.10774987 -0.1918078
   0.05852881 -0.40281653  0.30498155  0.82809572]
 [ 0.74801245 -2.8544615   0.04439682 -0.41496501 -0.44598552  0.24824484
  -0.40281653  0.0259355   1.45293608 -3.32286717]
 [ 

In [109]:
# eigen decomposition; 
w, v = np.linalg.eig(A)

In [110]:
print w

[-6.72620567  7.97027148 -3.88820678  4.75911966 -1.88797393  3.18766803
  1.84159198 -0.15515913  0.67579979  0.53621156]


In [111]:
print v

[[ 0.16018559  0.21964111  0.01683401  0.14142205 -0.03646813  0.01609614
   0.30535875  0.22446827  0.46681611  0.73666717]
 [-0.56726542 -0.6025265  -0.10717006 -0.26040628 -0.00561048  0.33926409
   0.26496649  0.13698498  0.14417025  0.10481472]
 [ 0.60373411 -0.54115107  0.22749332 -0.31778194 -0.24430168 -0.01151424
  -0.12770535 -0.02739222 -0.20591011  0.26579732]
 [ 0.05658673  0.06258832 -0.06329369  0.26069732 -0.25125458  0.13995079
   0.70077413 -0.18963982 -0.5572307   0.02535094]
 [-0.24082331 -0.08532059  0.01329697 -0.17041998  0.46186789 -0.60777543
   0.07953321 -0.3462704  -0.24139615  0.37187499]
 [ 0.07277137  0.1313827   0.42954291 -0.45617106 -0.06356207 -0.27618639
   0.4986694   0.02968789  0.31842945 -0.39188628]
 [ 0.04827852 -0.09974855 -0.10654528  0.09803999 -0.18938308  0.1139983
  -0.01055534 -0.85028458  0.44066351 -0.02478895]
 [-0.40081225  0.39135868  0.33387776 -0.33054289 -0.48861124  0.12995856
  -0.26286432 -0.13517176 -0.20813581  0.28130982]
 

In [112]:
# represent a matrix by eigenvectors and values. 
A2 = np.dot(np.dot(v, np.diag(w)), v.T)

In [116]:
print np.linalg.norm(A-A2)
print A - A2

1.15473453629e-14
[[ -5.55111512e-16  -9.99200722e-16   1.77635684e-15  -7.21644966e-16
    1.94289029e-16   1.80411242e-16   3.46944695e-16  -4.44089210e-16
   -4.30211422e-16  -6.38378239e-16]
 [ -1.05471187e-15   4.44089210e-15   2.66453526e-15  -4.78783679e-16
    1.33226763e-15  -1.66533454e-15   2.22044605e-16   0.00000000e+00
   -1.11022302e-16   1.47451495e-15]
 [  1.77635684e-15   2.66453526e-15   2.49800181e-15  -2.22044605e-16
    2.22044605e-16   0.00000000e+00   5.03069808e-16  -3.55271368e-15
    1.77635684e-15  -8.88178420e-16]
 [ -7.77156117e-16  -4.85722573e-16  -2.22044605e-16  -1.11022302e-15
    8.95117314e-16  -6.59194921e-16   4.44089210e-16   2.77555756e-16
   -9.99200722e-16  -6.66133815e-16]
 [  2.08166817e-16   1.33226763e-15   2.22044605e-16   8.39606162e-16
   -1.44328993e-15   1.11022302e-16  -7.63278329e-16  -6.66133815e-16
    1.11022302e-15   2.77555756e-16]
 [  1.52655666e-16  -1.55431223e-15   3.33066907e-16  -6.45317133e-16
    1.11022302e-16   1.3322