In [2]:
import numpy as np

n = 5
X = np.random.randn(n, n)

print X

A = np.dot(X.T, X)
print A

[[ 0.89812647 -1.24756607 -1.26709724  1.83639309  0.29607544]
 [ 0.25650231  0.72196564  0.38919976  0.49833214 -0.05566549]
 [-0.70803598 -0.23442317 -1.9906303   0.1423248  -0.98948773]
 [-1.12005866 -0.63582192  1.1019693   0.89007607 -1.70789161]
 [-1.65784423  0.44395641 -1.46718516 -0.47263358  0.61927302]]
[[ 5.37671843 -0.79315895  1.56934914  1.46298097  1.83850835]
 [-0.79315895  2.73397652  0.97640375 -2.74036585  1.18324176]
 [ 1.56934914  0.97640375  9.08658947 -0.74197645 -1.21774941]
 [ 1.46298097 -2.74036585 -0.74197645  4.65654878 -1.43770033]
 [ 1.83850835  1.18324176 -1.21774941 -1.43770033  4.37023809]]


In [3]:
w, v = np.linalg.eig(A)

In [4]:
print w
print v

[ 9.81417758  7.8773136   6.69011421  1.09273165  0.74973425]
[[-0.2419558   0.41277407  0.68422987 -0.54211476  0.09495278]
 [-0.14051097 -0.49693328  0.08608048 -0.05813092  0.85001466]
 [-0.9496458   0.04330384 -0.14598523  0.25514571 -0.09943146]
 [ 0.12383385  0.71638529 -0.06953749  0.4864315   0.47958965]
 [ 0.06746924 -0.2599842   0.70588418  0.63325938 -0.16901535]]


In [9]:
tmp = np.dot(A, v[:,1])

print tmp, '\n'

print v[:,0], '\n' 

print tmp / v[:,0],  '\n'

print w[0], '\n'

print v[:,1]

print tmp / v[:,1]

print w[1]

[ 3.25155078 -3.91449927  0.34111793  5.64319156 -2.04797709] 

[-0.2419558  -0.14051097 -0.9496458   0.12383385  0.06746924] 

[-13.43861497  27.85902892  -0.35920544  45.57067156 -30.35423454] 

9.81417757621 

[ 0.41277407 -0.49693328  0.04330384  0.71638529 -0.2599842 ]
[ 7.8773136  7.8773136  7.8773136  7.8773136  7.8773136]
7.8773136015


In [9]:
print v

[[-0.18671643  0.72437275 -0.08674484  0.62986958  0.19015979]
 [ 0.96019075  0.26779053  0.07860116 -0.01127513 -0.00408431]
 [ 0.14964269 -0.32483214 -0.67867529  0.459573   -0.44753062]
 [-0.02759865 -0.09820888  0.69530578  0.38176204 -0.60033404]
 [ 0.14147818 -0.53703952  0.20554055  0.49617295  0.63493146]]


In [10]:
print np.sum(v**2, axis=0)

[ 1.  1.  1.  1.  1.]


In [11]:
np.inner(v[:,4], v[:,0])

-6.9388939039072284e-17

In [10]:
B = np.zeros((n,n))

for i in range(n):
    B += w[i] * np.outer(v[:,i], v[:,i])
    
print B

print B - A

C = np.dot(v, np.dot(np.diag(w), v.T))

print C - A

[[ 5.37671843 -0.79315895  1.56934914  1.46298097  1.83850835]
 [-0.79315895  2.73397652  0.97640375 -2.74036585  1.18324176]
 [ 1.56934914  0.97640375  9.08658947 -0.74197645 -1.21774941]
 [ 1.46298097 -2.74036585 -0.74197645  4.65654878 -1.43770033]
 [ 1.83850835  1.18324176 -1.21774941 -1.43770033  4.37023809]]
[[  1.77635684e-15  -5.99520433e-15  -1.11022302e-15   5.77315973e-15
   -1.77635684e-15]
 [ -5.99520433e-15  -4.44089210e-16   4.44089210e-16   8.88178420e-16
    8.88178420e-16]
 [ -1.11022302e-15   4.44089210e-16   0.00000000e+00   4.44089210e-16
   -1.11022302e-15]
 [  5.77315973e-15   8.88178420e-16   4.44089210e-16  -8.88178420e-16
    1.55431223e-15]
 [ -1.77635684e-15   8.88178420e-16  -1.11022302e-15   1.55431223e-15
    8.88178420e-16]]
[[  8.88178420e-16  -5.55111512e-15  -4.44089210e-16   5.77315973e-15
   -1.77635684e-15]
 [ -5.99520433e-15  -4.44089210e-16   4.44089210e-16   8.88178420e-16
    8.88178420e-16]
 [ -8.88178420e-16   4.44089210e-16   1.77635684e-15 

[[ 0.86721914 -1.36912852  0.44304967 -0.66241253  0.87532642]
 [-1.08528401 -1.18894525  1.03007369  0.47895733  0.14955042]
 [-1.03995399 -0.55869138 -0.55088416 -0.94233162  1.26596557]]
[[ 3.01141473  0.68402213 -0.16080718 -0.11428003 -0.71975079]
 [ 0.68402213  3.60023975 -1.52351893  0.8639464  -2.08352566]
 [-0.16080718 -1.52351893  1.56081818  0.71899525 -0.15553935]
 [-0.11428003  0.8639464   0.71899525  1.55617937 -1.70115831]
 [-0.71975079 -2.08352566 -0.15553935 -1.70115831  2.39123048]]
[[-0.59720171  0.28241878 -0.75072614]
 [-0.5012301  -0.86210899  0.07440756]
 [-0.62619366  0.42072286  0.65640976]]
[ 2.49954155  1.76654663  1.65876084]
[[ 0.27096363  0.70550139 -0.1744055   0.29829797 -0.5562801 ]
 [ 0.42060574  0.22828638 -0.56306456 -0.56406754  0.36845929]
 [-0.85270482  0.34522372 -0.3723077  -0.0516212   0.11152265]
 [ 0.13213387 -0.23058103 -0.51966829  0.74093229  0.3321705 ]
 [ 0.07144685  0.52707314  0.49383486  0.20297962  0.65727898]]


In [35]:
n = 5
d = 3
X = np.random.randn(d, n)

A = np.dot(X.T, X)

u, s, v = np.linalg.svd(X)
v1 = v

print s

w, v = np.linalg.eigh(A)
v2 = v

print w


B = np.zeros((d,n))

for i in range(d):    
    B += s[i] * np.outer(u[:,i], v1[i,:])
    
print B - X    
    
    
    

[ 3.65236847  2.36433368  1.86587289]
[ -1.17438042e-15   6.41573994e-17   3.48148164e+00   5.59007376e+00
   1.33397955e+01]
[[  2.22044605e-15  -4.44089210e-16   4.44089210e-16   3.88578059e-16
   -3.33066907e-16]
 [ -5.55111512e-16  -1.33226763e-15   2.22044605e-16  -3.33066907e-16
    5.55111512e-16]
 [ -1.11022302e-16   3.05311332e-16  -2.08166817e-16   2.22044605e-16
    2.22044605e-16]]
